#!/usr/bin/env bash

BASE=`readlink -f $(dirname "${BASH_SOURCE-$0}")/..`

CONF=conf
CONF_DIR=${CONF_DIR:-$BASE/$CONF}

if [ -z $JAVA_HOME ]; then
    echo JAVA_HOME is not set, trying to determine it 
    JAVA_HOME=`readlink -f $(dirname $(readlink -f $(which java)))/..`
    JAVA_HOME_SET=true
fi

if [ $JAVA_HOME_SET ]; then
    echo Java found at $JAVA_HOME
fi

if [ -z $JAVA_HOME ]; then
    echo You should install Java and set JAVA_HOME
    exit
fi    

JAVA=$JAVA_HOME/bin/java

if [ -z '$SNACKFS_JAVA_OPTS' ]; then
    SNACKFS_JAVA_OPTS="-Xms1024m -Xmx1024m"
fi

CLASSPATH="${CONF_DIR}"
CLASSPATH=${CLASSPATH}:$JAVA_HOME/lib/tools.jar

# add libs to CLASSPATH
for f in $BASE/lib/*.jar; do
  CLASSPATH=${CLASSPATH}:$f;
done

OPTS=""
exec "$JAVA" -Dproc_$COMMAND $SNACKFS_JAVA_OPTS $OPTS -classpath "$CLASSPATH" org.apache.hadoop.fs.SnackFSShell "$@"


